### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by EdwardAngert** [EdwardAngert/Strata-Jekyll-Theme#1]
- [ ] check configs for variables
  - [ ] update yaml
  - [ ] update about
- [ ] is there a migrate option/flow?
- [ ] scrape posts / template info
- [ ] point dns?
